package milnet

import (
	"math/rand"

	"github.com/encse/altnet/ent/schema"
	"github.com/encse/altnet/lib/slices"
)

func RandomWord() string {
	return slices.ChooseX(thelist)
}

const alphabet = "ABCDEFHIJKLMNOPQRSTUVWXY23456789"

const UserIdPrompt = "User-Id:"
const PasswordPrompt = "Access Code:"

// GenerateUserId CER5-ISIE or MRW1-ISIE
func GenerateUserId() schema.Uname {
	return schema.Uname(generateWord(alphabet, 4) + "-ISI" + generateWord("ABCDEF", 1))
}

// GenerateAccessCode 2285UNG6A or 22L8KK5CH
func GenerateAccessCode() schema.Password {
	return schema.Password(generateWord(alphabet, 9))
}

func generateWord(alphabet string, length int) string {
	res := ""
	for i := 0; i < length; i++ {
		res += string(alphabet[rand.Intn(len(alphabet))])
	}
	return res
}

var thelist = []string{
	"ANI 4",
	" LL MOVE",
	" u 1000$0111b",
	"-asims.army.mil",
	"-giis.army.mil",
	"-gw.af.mil",
	"-med.af.mil",
	"-ngnet.army.mil",
	"-pac-gw.navy.mil",
	",FIGHTW,FOOW",
	",TRNFLG",
	": ILDB T3,T1",
	".af.mil",
	".army.mil",
	".arpa",
	".drms.dla.mil",
	".navy.mil",
	"'",
	"' '",
	"'++READ ERROR OR EARLY EOF$'",
	"'+80H",
	"'BCDEHLMA'",
	"'ENDI'",
	"'P",
	"(*=24hr/R=ring back)",
	"*",
	"=============================',CR,LF",
	"0,35,36)",
	"0.ddn.mil",
	"1-gw.af.mil",
	"1.army.mil",
	"FCPT CALL CKABORT",
	"2.mt.ddn.mil",
	"20.ddn.mil",
	"200H",
	"3292olph2.mt.ddn.mil",
	"4 EQU 0011B",
	"table",
	"af.mil",
	"ah,prstr",
	"alexandria.mt.ddn.mil",
	"ALL IHX(2,PC,7)",
	"ALL SCRN",
	"amb19-t20.disa.mil",
	"ANI 0FH",
	"army.mil",
	"asms.af.mil",
	"avy.mil",
	"B",
	"B CR,LF",
	"b seqio",
	"B$MAX:",
	"++ Bad library number called ++",
	"badkreuzn-emh1.army.m,CR,LF",
	"BATCHFLG DB TRUE",
	"BBERED ++$'",
	"BC,LOCATE,LOCPAG,LOCPNT,LOKSUP,LOWBFR,NSKIP ,",
	"BCAL",
	"bn.army.mil",
	"brams.mt.ddn.mil",
	"c.navy.mil",
	"CALL",
	"CALL DECPT",
	"call epsi",
	"call gbyt",
	"CALL KDELAY",
	"CALL MTEST",
	"CALL REC87E248A",
	"CALL SENDACK",
	"call TWOL",
	"CALL TYPE",
	"call xref",
	"CAML T2,Q2",
	"CBLK",
	"ccsu.navy.mil",
	"chantilly1.mt.ddn.mil",
	"CHLP",
	"CMP M",
	"COLON:",
	"cpds-oakridge3.navy.mil",
	"cts-gw4.navy.mil",
	"CVSERR",
	"d-gw.sssd.navy.mil",
	"D,DEC",
	"D,FCB2",
	"D,FNAME+9",
	"d,rsiz",
	"DAD D",
	"dad h",
	"DB '?'+80H",
	"DB 'BLOC'",
	"DB 'PF'",
	"DB 'V'",
	"DB 0,0,0,0,0,0",
	"db 3bh",
	"esc.dlanet.dla.mil",
	"DCR A",
	"DCR B",
	"dd.army.mil",
	"JZ INST2",
	"ddn.mil",
	"DEC",
	"SPECIAL",
	"DF5224",
	"DI A,LF",
	"DIAL8",
	"dn.mil",
	"dr1",
	"DSPHEX",
	"DW BUF1",
	"DW INDEX-8",
	"DW STOD",
	"ed.navy.mits-gw.navy.mil",
	"edcars-wp.af.mil",
	"EEFLG:",
	"EF444k-emh1.army.mil",
	"ego.mt.ddn.mil",
	"el-segundo.mt.ddn.mil",
	"elly1-gw.af.mil",
	"emh1.army.mil",
	"END",
	"eocu-gw.navy.mil",
	"ERXIT:",
	"et-buckner.army.mil",
	"ett.mt.ddn.milo-am1.af.mil",
	"ev.navy.mil",
	"EXITTST1:",
	"f-izmir.af.mil",
	"FCHK: ",
	"XCHG",
	"fincc-gw.af.mil",
	"futt2-gw.af.mil",
	"g.dlacolan.dla.mil",
	"gablingen.mmt.ddn.mil",
	"GBCD",
	"gdss.af.mil",
	"gw.af.mil",
	"gw.army.mil",
	"gw.desc.dla.mil",
	"gw1.army.mil",
	"h-gw.af.mil",
	"h-poe.arpa",
	"H,20H",
	"H,OPTBL",
	"h.mt.ddn.mil",
	"hahran-gw1.army.mil",
	"hanscom2.mt.ddn.mil",
	"heim-emh2.army.mil",
	"hh: call epsi",
	"I 1AH",
	"I E,CONSTA",
	"I:",
	"ic-gw.dtic.dla.mil",
	"icenza-gw1.army.mil",
	"idelberg-emh1.army.mil",
	"iego-bumed.navy.mil",
	"IF MICROP",
	"ific.drms.dlcmdw.dla.mil",
	"ilprt",
	"in data",
	"ing-gw.af.mil",
	"INR M",
	"DW QSTAC",
	"INX D",
	"INX H",
	"ISPACE",
	"issom-gw.af.mil",
	"jc dido",
	"jmp clist1",
	"JMP DILAGN",
	"jmp error",
	"JMP PAST",
	"jmp txsabm",
	"JNZ L1006",
	"JNZ YCHECK",
	"JRC PRNLE",
	"JZ GHW4",
	"JZ MAIN04",
	"JZ RBOOT",
	"JZ,.JRZ",
	"kam-gw.af.mil",
	"klion-gw.af.mil",
	"L GETSBIT",
	"l-jacs6343.army.mil",
	"langley-r01.af.mil",
	"LCRLF0:",
	"ld bx,RX",
	"LDA 7",
	"LDA ORIGFLG",
	"LES2-$",
	"LL BDOS",
	"LL KEYIN",
	"LL RECV",
	"LLF,CPOUTF",
	"LOCDOT",
	"LRUN [-<lbrname>] <command line>'",
	"LXI D,CMDBUF+2",
	"LXI D,IBUF-1",
	"lxi d,nodi",
	"madc.dma.mil",
	"masens-ignet.army.mil",
	"mb.af.mil",
	"mc2.disa.mil",
	"mcclellan-asatms1.army.mil",
	"memfcb: ds PUSHJ P,INLMES",
	"MFFLG1 A",
	"MITEST: IN MODS",
	"mov a,c",
	"MOV A,L",
	"MOV A,M",
	"MOV B,M",
	"MOV C,A",
	"MOV C,L",
	"mov m,d",
	"MOVE",
	"MOVE T3,ADDTKT",
	"MP PH1",
	"mphry-jacs5480.army.mil",
	"msa-sandiego2.navy.mil",
	"mt.ddn.mil",
	"MTX FILE FROM B:',CR,LF",
	"MVI A,0FH",
	"MVI B,CTIME*10",
	"MVI C,11",
	"MVI C,AETX",
	"MWTI: CALL IN$MODCTLP",
	"my.mil",
	"N USER AREAS",
	"n-gw.navy.milore-buarl.army.mil",
	"n-ignet.army.milon.mt.ddn.mil",
	"n.mil",
	"n.mmt.ddn.mil",
	"nadn-net-gw.navy.mil",
	"navy.mil",
	"ndc.navy.mil",
	"ndolph2.mt.ddn.mil",
	"ne-gw1.army.mil",
	"NEWBAUD1",
	"ngeles-gw.af.mil",
	"ngerli.army.mil",
	"NODEST",
	"NOLIST CALL CROSSCK",
	"nosc-gw.nosc.mil",
	"npmocw-gw.navy.mil",
	"nsvillet20.ddn.mil",
	"oc-gw.navy.mil",
	"od.memphis.drms.dla.mil",
	"ods2-gw1.army.mil",
	"OF EACH PAGE (Y/N)? '",
	"okosuka.mt.ddn.mil",
	"ora a",
	"ORA A",
	"ORG",
	"ORG 100H",
	"ori 080H",
	"ORI 1",
	"ov a,c",
	"OV D,M",
	"OV E,M",
	"OVE N,POINT-1(X1)]",
	"ox-gw1.army.mil",
	"P",
	"P OUTER",
	"pmsa-corpus1.navy.mil",
	"POP",
	"POP D",
	"pop h",
	"PSW",
	"PUSH B",
	"PUSH D",
	"PUSH H",
	"q3data",
	"r-gw.af.mil",
	"rdec-gw2.army.mil",
	"RESTSN:",
	"ret",
	"RET",
	"RETURN",
	"RITE = 42",
	"rk-gw.af.mil",
	"rl.dla.mil",
	"rmy.mil",
	"RNZ",
	"rpa05.nav621F129",
	"rs-asmo.navy.mil",
	"rxbccpds-pwcpearl.navy.mil",
	"s-am1.af.mil",
	"s-gw.af.mil",
	"s-gw3.army.mil",
	"s.af.mil",
	"s.army.mil",
	"s.dla.mil",
	"s.mt.ddn.mil",
	"S80=0",
	"SAMJM1= P+446",
	"satms.army. SECTNO",
	"sc.dla.mil",
	"SELDSK DATDSK1",
	"sey-jacs6311.army.mil",
	"SHLD BBUF+2",
	"si-gw.disa.mil",
	"STA DISKNO",
	"STA FILESW",
	"ston-gw.army.mil",
	"SUB M",
	"t-inigoes.mt.ddn.mil",
	"t.ddn.mil",
	"tainhome-gw.af.mil",
	"TBL",
	"tchie-mb.ddn.mil",
	"TO 100",
	"TOR",
	"TRANLOGON: DB TRUE",
	"trf.navy.mAAC0B",
	"TRHFL/ 155004020100,1HU/",
	"umed.navy.mil",
	"urtonwood-emh1.army.mil",
	"usasoc.soc.mil",
	"V A,L",
	"V E,A",
	"v.af.mil",
	"VI C,16H",
	"ville-bumed.navy.mil",
	"vres.mmt.ddn.mil",
	"vy.mil",
	"W 00",
	"W ERROR2",
	"w.af.mil",
	"w.oc.aflc.af.mil",
	"w1.army.mil",
	"ward.gte-pac.com",
	"westpoint-gw.army.miln.mil",
	"WRITE(NPRNT,100)",
	"xgate.med.osd.mil",
	"XI B,CMDADD-CMDTBL+1",
	"xi2E735",
	"y.mil",
	"ynchbrg-dlacolan.dla.mil",
	"Z RCVSQ",
}
