#!/bin/bash

echo -e '\033[36m
                           ##        .
                     ## ## ##       ==
                  ## ## ## ##      ===
              /""""""""""""""""\___/ ===
       \033[36m  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
              \______ o          __/
                \    \        __/
                 \____\______/\033[0m'
tput sgr0

USAGE='
  service \033[31mstart\033[0m - start the environment
  service \033[31mkick\033[0m - restarts the environment
  service \033[31mlogs\033[0m - watch the Docker logs

  service \033[31mshell\033[0m - runs the container with an interactive shell 
  service \033[31mbuild\033[0m - build container
'

export DOCKER_BUILDKIT=1 
source ./env

function start() {
    docker-compose build
    CURRENT_UID=$(id -u www-data):$(id -g www-data) docker-compose up --detach --remove-orphans
}

function dev() {
    stop
    docker-compose build
    CURRENT_UID=0:0 docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --remove-orphans -d
}

# start with ./service dev, then run ./service gobuild to rebuild all cmds
function gobuild() {
    docker exec -w /src altnet go install -ldflags="-s -w"  ./cmd/...
}

function stop() {
    echo -e "stopping"
    docker-compose down
}

function restart() {
    stop && start
}

function console() {
    docker exec -e ALTNET_HOST=csokavar -e ALTNET_USER=guest -it altnet ./shell
}

function bash() {
    docker exec -it altnet /bin/bash
}

function logs() {
    docker logs --follow altnet
}

function usage() {
    echo -e "$USAGE"
    tput sgr0
    exit 1
}

if ! type "$1" >/dev/null 2>&1; then usage; else $1; fi
