#!/bin/bash

echo -e '\033[36m
                           ##        .
                     ## ## ##       ==
                  ## ## ## ##      ===
              /""""""""""""""""\___/ ===
       \033[36m  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
              \______ o          __/
                \    \        __/
                 \____\______/\033[0m'
tput sgr0

USAGE='
  service \033[31mstart\033[0m - start the environment
  service \033[31mkick\033[0m - restarts the environment
  service \033[31mlogs\033[0m - watch the Docker logs

  service \033[31mshell\033[0m - runs the container with an interactive shell 
  service \033[31mbuild\033[0m - build container
'

export DOCKER_BUILDKIT=1 
source ./env

function start() {
    docker-compose build
    docker-compose up --detach --remove-orphans
}

function dev() {
    stop
    docker-compose build
    docker-compose up --remove-orphans
}

function stop() {
    echo -e "stopping"
    docker-compose down
}

function kick() {
    stop && start 
}

function logs() {
    docker logs --follow altnet
}

# function dev() {
#    stop
#    npx nodemon --watch 'src/**/*.*' --watch 'public/**/*.*' --exec 'npm run service'
# }

function usage() {
    echo -e "$USAGE"
    tput sgr0
    exit 1
}

if ! type "$1" >/dev/null 2>&1; then usage; else $1; fi
