// Code generated by ent, DO NOT EDIT.

package virtualuser

const (
	// Label holds the string label denoting the virtualuser type in the database.
	Label = "virtual_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUser holds the string denoting the user field in the database.
	FieldUser = "user"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// Table holds the table name of the virtualuser in the database.
	Table = "virtual_users"
)

// Columns holds all SQL columns for virtualuser fields.
var Columns = []string{
	FieldID,
	FieldUser,
	FieldPassword,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "virtual_users"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"host_virtualusers",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
