// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HostsColumns holds the columns for the "hosts" table.
	HostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"bbs", "uucp", "mil"}},
		{Name: "entry", Type: field.TypeString, Default: ""},
		{Name: "machine_type", Type: field.TypeString, Default: ""},
		{Name: "organization", Type: field.TypeString, Default: ""},
		{Name: "contact", Type: field.TypeString, Default: ""},
		{Name: "contact_address", Type: field.TypeString, Default: ""},
		{Name: "country", Type: field.TypeString, Default: ""},
		{Name: "location", Type: field.TypeString, Default: ""},
		{Name: "geo_location", Type: field.TypeString, Default: ""},
		{Name: "phone", Type: field.TypeJSON, Nullable: true},
		{Name: "neighbours", Type: field.TypeJSON, Nullable: true},
	}
	// HostsTable holds the schema information for the "hosts" table.
	HostsTable = &schema.Table{
		Name:       "hosts",
		Columns:    HostsColumns,
		PrimaryKey: []*schema.Column{HostsColumns[0]},
	}
	// JokesColumns holds the columns for the "jokes" table.
	JokesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "body", Type: field.TypeString},
		{Name: "category", Type: field.TypeString},
	}
	// JokesTable holds the schema information for the "jokes" table.
	JokesTable = &schema.Table{
		Name:       "jokes",
		Columns:    JokesColumns,
		PrimaryKey: []*schema.Column{JokesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HostsTable,
		JokesTable,
	}
)

func init() {
}
