// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/encse/altnet/ent/joke"
	"github.com/encse/altnet/ent/predicate"
)

// JokeUpdate is the builder for updating Joke entities.
type JokeUpdate struct {
	config
	hooks    []Hook
	mutation *JokeMutation
}

// Where appends a list predicates to the JokeUpdate builder.
func (ju *JokeUpdate) Where(ps ...predicate.Joke) *JokeUpdate {
	ju.mutation.Where(ps...)
	return ju
}

// SetBody sets the "body" field.
func (ju *JokeUpdate) SetBody(s string) *JokeUpdate {
	ju.mutation.SetBody(s)
	return ju
}

// SetCategory sets the "category" field.
func (ju *JokeUpdate) SetCategory(s string) *JokeUpdate {
	ju.mutation.SetCategory(s)
	return ju
}

// Mutation returns the JokeMutation object of the builder.
func (ju *JokeUpdate) Mutation() *JokeMutation {
	return ju.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ju *JokeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, JokeMutation](ctx, ju.sqlSave, ju.mutation, ju.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ju *JokeUpdate) SaveX(ctx context.Context) int {
	affected, err := ju.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ju *JokeUpdate) Exec(ctx context.Context) error {
	_, err := ju.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ju *JokeUpdate) ExecX(ctx context.Context) {
	if err := ju.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ju *JokeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(joke.Table, joke.Columns, sqlgraph.NewFieldSpec(joke.FieldID, field.TypeInt))
	if ps := ju.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ju.mutation.Body(); ok {
		_spec.SetField(joke.FieldBody, field.TypeString, value)
	}
	if value, ok := ju.mutation.Category(); ok {
		_spec.SetField(joke.FieldCategory, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ju.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{joke.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ju.mutation.done = true
	return n, nil
}

// JokeUpdateOne is the builder for updating a single Joke entity.
type JokeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JokeMutation
}

// SetBody sets the "body" field.
func (juo *JokeUpdateOne) SetBody(s string) *JokeUpdateOne {
	juo.mutation.SetBody(s)
	return juo
}

// SetCategory sets the "category" field.
func (juo *JokeUpdateOne) SetCategory(s string) *JokeUpdateOne {
	juo.mutation.SetCategory(s)
	return juo
}

// Mutation returns the JokeMutation object of the builder.
func (juo *JokeUpdateOne) Mutation() *JokeMutation {
	return juo.mutation
}

// Where appends a list predicates to the JokeUpdate builder.
func (juo *JokeUpdateOne) Where(ps ...predicate.Joke) *JokeUpdateOne {
	juo.mutation.Where(ps...)
	return juo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (juo *JokeUpdateOne) Select(field string, fields ...string) *JokeUpdateOne {
	juo.fields = append([]string{field}, fields...)
	return juo
}

// Save executes the query and returns the updated Joke entity.
func (juo *JokeUpdateOne) Save(ctx context.Context) (*Joke, error) {
	return withHooks[*Joke, JokeMutation](ctx, juo.sqlSave, juo.mutation, juo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (juo *JokeUpdateOne) SaveX(ctx context.Context) *Joke {
	node, err := juo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (juo *JokeUpdateOne) Exec(ctx context.Context) error {
	_, err := juo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (juo *JokeUpdateOne) ExecX(ctx context.Context) {
	if err := juo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (juo *JokeUpdateOne) sqlSave(ctx context.Context) (_node *Joke, err error) {
	_spec := sqlgraph.NewUpdateSpec(joke.Table, joke.Columns, sqlgraph.NewFieldSpec(joke.FieldID, field.TypeInt))
	id, ok := juo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Joke.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := juo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, joke.FieldID)
		for _, f := range fields {
			if !joke.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != joke.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := juo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := juo.mutation.Body(); ok {
		_spec.SetField(joke.FieldBody, field.TypeString, value)
	}
	if value, ok := juo.mutation.Category(); ok {
		_spec.SetField(joke.FieldCategory, field.TypeString, value)
	}
	_node = &Joke{config: juo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, juo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{joke.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	juo.mutation.done = true
	return _node, nil
}
