// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/encse/altnet/ent/joke"
)

// JokeCreate is the builder for creating a Joke entity.
type JokeCreate struct {
	config
	mutation *JokeMutation
	hooks    []Hook
}

// SetBody sets the "body" field.
func (jc *JokeCreate) SetBody(s string) *JokeCreate {
	jc.mutation.SetBody(s)
	return jc
}

// SetCategory sets the "category" field.
func (jc *JokeCreate) SetCategory(s string) *JokeCreate {
	jc.mutation.SetCategory(s)
	return jc
}

// SetID sets the "id" field.
func (jc *JokeCreate) SetID(i int) *JokeCreate {
	jc.mutation.SetID(i)
	return jc
}

// Mutation returns the JokeMutation object of the builder.
func (jc *JokeCreate) Mutation() *JokeMutation {
	return jc.mutation
}

// Save creates the Joke in the database.
func (jc *JokeCreate) Save(ctx context.Context) (*Joke, error) {
	return withHooks[*Joke, JokeMutation](ctx, jc.sqlSave, jc.mutation, jc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (jc *JokeCreate) SaveX(ctx context.Context) *Joke {
	v, err := jc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jc *JokeCreate) Exec(ctx context.Context) error {
	_, err := jc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jc *JokeCreate) ExecX(ctx context.Context) {
	if err := jc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jc *JokeCreate) check() error {
	if _, ok := jc.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Joke.body"`)}
	}
	if _, ok := jc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Joke.category"`)}
	}
	return nil
}

func (jc *JokeCreate) sqlSave(ctx context.Context) (*Joke, error) {
	if err := jc.check(); err != nil {
		return nil, err
	}
	_node, _spec := jc.createSpec()
	if err := sqlgraph.CreateNode(ctx, jc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	jc.mutation.id = &_node.ID
	jc.mutation.done = true
	return _node, nil
}

func (jc *JokeCreate) createSpec() (*Joke, *sqlgraph.CreateSpec) {
	var (
		_node = &Joke{config: jc.config}
		_spec = sqlgraph.NewCreateSpec(joke.Table, sqlgraph.NewFieldSpec(joke.FieldID, field.TypeInt))
	)
	if id, ok := jc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := jc.mutation.Body(); ok {
		_spec.SetField(joke.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := jc.mutation.Category(); ok {
		_spec.SetField(joke.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	return _node, _spec
}

// JokeCreateBulk is the builder for creating many Joke entities in bulk.
type JokeCreateBulk struct {
	config
	builders []*JokeCreate
}

// Save creates the Joke entities in the database.
func (jcb *JokeCreateBulk) Save(ctx context.Context) ([]*Joke, error) {
	specs := make([]*sqlgraph.CreateSpec, len(jcb.builders))
	nodes := make([]*Joke, len(jcb.builders))
	mutators := make([]Mutator, len(jcb.builders))
	for i := range jcb.builders {
		func(i int, root context.Context) {
			builder := jcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JokeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, jcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, jcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, jcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (jcb *JokeCreateBulk) SaveX(ctx context.Context) []*Joke {
	v, err := jcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jcb *JokeCreateBulk) Exec(ctx context.Context) error {
	_, err := jcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jcb *JokeCreateBulk) ExecX(ctx context.Context) {
	if err := jcb.Exec(ctx); err != nil {
		panic(err)
	}
}
