// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/encse/altnet/ent/host"
	"github.com/encse/altnet/ent/joke"
	"github.com/encse/altnet/ent/predicate"
	"github.com/encse/altnet/ent/tcpservice"
	"github.com/encse/altnet/ent/user"
	"github.com/encse/altnet/ent/virtualuser"
	"github.com/encse/altnet/schema"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeHost        = "Host"
	TypeJoke        = "Joke"
	TypeTcpService  = "TcpService"
	TypeUser        = "User"
	TypeVirtualUser = "VirtualUser"
)

// HostMutation represents an operation that mutates the Host nodes in the graph.
type HostMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int
	name                *schema.HostName
	_type               *host.Type
	entry               *string
	machine_type        *string
	organization        *string
	contact             *string
	contact_address     *string
	country             *string
	location            *string
	geo_location        *string
	phone               *[]schema.PhoneNumber
	appendphone         []schema.PhoneNumber
	neighbours          *[]schema.HostName
	appendneighbours    []schema.HostName
	clearedFields       map[string]struct{}
	services            map[int]struct{}
	removedservices     map[int]struct{}
	clearedservices     bool
	virtualusers        map[int]struct{}
	removedvirtualusers map[int]struct{}
	clearedvirtualusers bool
	hackers             map[int]struct{}
	removedhackers      map[int]struct{}
	clearedhackers      bool
	done                bool
	oldValue            func(context.Context) (*Host, error)
	predicates          []predicate.Host
}

var _ ent.Mutation = (*HostMutation)(nil)

// hostOption allows management of the mutation configuration using functional options.
type hostOption func(*HostMutation)

// newHostMutation creates new mutation for the Host entity.
func newHostMutation(c config, op Op, opts ...hostOption) *HostMutation {
	m := &HostMutation{
		config:        c,
		op:            op,
		typ:           TypeHost,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withHostID sets the ID field of the mutation.
func withHostID(id int) hostOption {
	return func(m *HostMutation) {
		var (
			err   error
			once  sync.Once
			value *Host
		)
		m.oldValue = func(ctx context.Context) (*Host, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Host.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withHost sets the old Host of the mutation.
func withHost(node *Host) hostOption {
	return func(m *HostMutation) {
		m.oldValue = func(context.Context) (*Host, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m HostMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m HostMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *HostMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *HostMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Host.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *HostMutation) SetName(sn schema.HostName) {
	m.name = &sn
}

// Name returns the value of the "name" field in the mutation.
func (m *HostMutation) Name() (r schema.HostName, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldName(ctx context.Context) (v schema.HostName, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *HostMutation) ResetName() {
	m.name = nil
}

// SetType sets the "type" field.
func (m *HostMutation) SetType(h host.Type) {
	m._type = &h
}

// GetType returns the value of the "type" field in the mutation.
func (m *HostMutation) GetType() (r host.Type, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldType(ctx context.Context) (v host.Type, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *HostMutation) ResetType() {
	m._type = nil
}

// SetEntry sets the "entry" field.
func (m *HostMutation) SetEntry(s string) {
	m.entry = &s
}

// Entry returns the value of the "entry" field in the mutation.
func (m *HostMutation) Entry() (r string, exists bool) {
	v := m.entry
	if v == nil {
		return
	}
	return *v, true
}

// OldEntry returns the old "entry" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldEntry(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEntry is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEntry requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEntry: %w", err)
	}
	return oldValue.Entry, nil
}

// ResetEntry resets all changes to the "entry" field.
func (m *HostMutation) ResetEntry() {
	m.entry = nil
}

// SetMachineType sets the "machine_type" field.
func (m *HostMutation) SetMachineType(s string) {
	m.machine_type = &s
}

// MachineType returns the value of the "machine_type" field in the mutation.
func (m *HostMutation) MachineType() (r string, exists bool) {
	v := m.machine_type
	if v == nil {
		return
	}
	return *v, true
}

// OldMachineType returns the old "machine_type" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldMachineType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMachineType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMachineType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMachineType: %w", err)
	}
	return oldValue.MachineType, nil
}

// ResetMachineType resets all changes to the "machine_type" field.
func (m *HostMutation) ResetMachineType() {
	m.machine_type = nil
}

// SetOrganization sets the "organization" field.
func (m *HostMutation) SetOrganization(s string) {
	m.organization = &s
}

// Organization returns the value of the "organization" field in the mutation.
func (m *HostMutation) Organization() (r string, exists bool) {
	v := m.organization
	if v == nil {
		return
	}
	return *v, true
}

// OldOrganization returns the old "organization" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldOrganization(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOrganization is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOrganization requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrganization: %w", err)
	}
	return oldValue.Organization, nil
}

// ResetOrganization resets all changes to the "organization" field.
func (m *HostMutation) ResetOrganization() {
	m.organization = nil
}

// SetContact sets the "contact" field.
func (m *HostMutation) SetContact(s string) {
	m.contact = &s
}

// Contact returns the value of the "contact" field in the mutation.
func (m *HostMutation) Contact() (r string, exists bool) {
	v := m.contact
	if v == nil {
		return
	}
	return *v, true
}

// OldContact returns the old "contact" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldContact(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContact is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContact requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContact: %w", err)
	}
	return oldValue.Contact, nil
}

// ResetContact resets all changes to the "contact" field.
func (m *HostMutation) ResetContact() {
	m.contact = nil
}

// SetContactAddress sets the "contact_address" field.
func (m *HostMutation) SetContactAddress(s string) {
	m.contact_address = &s
}

// ContactAddress returns the value of the "contact_address" field in the mutation.
func (m *HostMutation) ContactAddress() (r string, exists bool) {
	v := m.contact_address
	if v == nil {
		return
	}
	return *v, true
}

// OldContactAddress returns the old "contact_address" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldContactAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContactAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContactAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContactAddress: %w", err)
	}
	return oldValue.ContactAddress, nil
}

// ResetContactAddress resets all changes to the "contact_address" field.
func (m *HostMutation) ResetContactAddress() {
	m.contact_address = nil
}

// SetCountry sets the "country" field.
func (m *HostMutation) SetCountry(s string) {
	m.country = &s
}

// Country returns the value of the "country" field in the mutation.
func (m *HostMutation) Country() (r string, exists bool) {
	v := m.country
	if v == nil {
		return
	}
	return *v, true
}

// OldCountry returns the old "country" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldCountry(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCountry is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCountry requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCountry: %w", err)
	}
	return oldValue.Country, nil
}

// ResetCountry resets all changes to the "country" field.
func (m *HostMutation) ResetCountry() {
	m.country = nil
}

// SetLocation sets the "location" field.
func (m *HostMutation) SetLocation(s string) {
	m.location = &s
}

// Location returns the value of the "location" field in the mutation.
func (m *HostMutation) Location() (r string, exists bool) {
	v := m.location
	if v == nil {
		return
	}
	return *v, true
}

// OldLocation returns the old "location" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldLocation(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLocation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLocation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLocation: %w", err)
	}
	return oldValue.Location, nil
}

// ResetLocation resets all changes to the "location" field.
func (m *HostMutation) ResetLocation() {
	m.location = nil
}

// SetGeoLocation sets the "geo_location" field.
func (m *HostMutation) SetGeoLocation(s string) {
	m.geo_location = &s
}

// GeoLocation returns the value of the "geo_location" field in the mutation.
func (m *HostMutation) GeoLocation() (r string, exists bool) {
	v := m.geo_location
	if v == nil {
		return
	}
	return *v, true
}

// OldGeoLocation returns the old "geo_location" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldGeoLocation(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGeoLocation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGeoLocation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGeoLocation: %w", err)
	}
	return oldValue.GeoLocation, nil
}

// ResetGeoLocation resets all changes to the "geo_location" field.
func (m *HostMutation) ResetGeoLocation() {
	m.geo_location = nil
}

// SetPhone sets the "phone" field.
func (m *HostMutation) SetPhone(sn []schema.PhoneNumber) {
	m.phone = &sn
	m.appendphone = nil
}

// Phone returns the value of the "phone" field in the mutation.
func (m *HostMutation) Phone() (r []schema.PhoneNumber, exists bool) {
	v := m.phone
	if v == nil {
		return
	}
	return *v, true
}

// OldPhone returns the old "phone" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldPhone(ctx context.Context) (v []schema.PhoneNumber, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPhone is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPhone requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPhone: %w", err)
	}
	return oldValue.Phone, nil
}

// AppendPhone adds sn to the "phone" field.
func (m *HostMutation) AppendPhone(sn []schema.PhoneNumber) {
	m.appendphone = append(m.appendphone, sn...)
}

// AppendedPhone returns the list of values that were appended to the "phone" field in this mutation.
func (m *HostMutation) AppendedPhone() ([]schema.PhoneNumber, bool) {
	if len(m.appendphone) == 0 {
		return nil, false
	}
	return m.appendphone, true
}

// ClearPhone clears the value of the "phone" field.
func (m *HostMutation) ClearPhone() {
	m.phone = nil
	m.appendphone = nil
	m.clearedFields[host.FieldPhone] = struct{}{}
}

// PhoneCleared returns if the "phone" field was cleared in this mutation.
func (m *HostMutation) PhoneCleared() bool {
	_, ok := m.clearedFields[host.FieldPhone]
	return ok
}

// ResetPhone resets all changes to the "phone" field.
func (m *HostMutation) ResetPhone() {
	m.phone = nil
	m.appendphone = nil
	delete(m.clearedFields, host.FieldPhone)
}

// SetNeighbours sets the "neighbours" field.
func (m *HostMutation) SetNeighbours(sn []schema.HostName) {
	m.neighbours = &sn
	m.appendneighbours = nil
}

// Neighbours returns the value of the "neighbours" field in the mutation.
func (m *HostMutation) Neighbours() (r []schema.HostName, exists bool) {
	v := m.neighbours
	if v == nil {
		return
	}
	return *v, true
}

// OldNeighbours returns the old "neighbours" field's value of the Host entity.
// If the Host object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HostMutation) OldNeighbours(ctx context.Context) (v []schema.HostName, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNeighbours is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNeighbours requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNeighbours: %w", err)
	}
	return oldValue.Neighbours, nil
}

// AppendNeighbours adds sn to the "neighbours" field.
func (m *HostMutation) AppendNeighbours(sn []schema.HostName) {
	m.appendneighbours = append(m.appendneighbours, sn...)
}

// AppendedNeighbours returns the list of values that were appended to the "neighbours" field in this mutation.
func (m *HostMutation) AppendedNeighbours() ([]schema.HostName, bool) {
	if len(m.appendneighbours) == 0 {
		return nil, false
	}
	return m.appendneighbours, true
}

// ClearNeighbours clears the value of the "neighbours" field.
func (m *HostMutation) ClearNeighbours() {
	m.neighbours = nil
	m.appendneighbours = nil
	m.clearedFields[host.FieldNeighbours] = struct{}{}
}

// NeighboursCleared returns if the "neighbours" field was cleared in this mutation.
func (m *HostMutation) NeighboursCleared() bool {
	_, ok := m.clearedFields[host.FieldNeighbours]
	return ok
}

// ResetNeighbours resets all changes to the "neighbours" field.
func (m *HostMutation) ResetNeighbours() {
	m.neighbours = nil
	m.appendneighbours = nil
	delete(m.clearedFields, host.FieldNeighbours)
}

// AddServiceIDs adds the "services" edge to the TcpService entity by ids.
func (m *HostMutation) AddServiceIDs(ids ...int) {
	if m.services == nil {
		m.services = make(map[int]struct{})
	}
	for i := range ids {
		m.services[ids[i]] = struct{}{}
	}
}

// ClearServices clears the "services" edge to the TcpService entity.
func (m *HostMutation) ClearServices() {
	m.clearedservices = true
}

// ServicesCleared reports if the "services" edge to the TcpService entity was cleared.
func (m *HostMutation) ServicesCleared() bool {
	return m.clearedservices
}

// RemoveServiceIDs removes the "services" edge to the TcpService entity by IDs.
func (m *HostMutation) RemoveServiceIDs(ids ...int) {
	if m.removedservices == nil {
		m.removedservices = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.services, ids[i])
		m.removedservices[ids[i]] = struct{}{}
	}
}

// RemovedServices returns the removed IDs of the "services" edge to the TcpService entity.
func (m *HostMutation) RemovedServicesIDs() (ids []int) {
	for id := range m.removedservices {
		ids = append(ids, id)
	}
	return
}

// ServicesIDs returns the "services" edge IDs in the mutation.
func (m *HostMutation) ServicesIDs() (ids []int) {
	for id := range m.services {
		ids = append(ids, id)
	}
	return
}

// ResetServices resets all changes to the "services" edge.
func (m *HostMutation) ResetServices() {
	m.services = nil
	m.clearedservices = false
	m.removedservices = nil
}

// AddVirtualuserIDs adds the "virtualusers" edge to the VirtualUser entity by ids.
func (m *HostMutation) AddVirtualuserIDs(ids ...int) {
	if m.virtualusers == nil {
		m.virtualusers = make(map[int]struct{})
	}
	for i := range ids {
		m.virtualusers[ids[i]] = struct{}{}
	}
}

// ClearVirtualusers clears the "virtualusers" edge to the VirtualUser entity.
func (m *HostMutation) ClearVirtualusers() {
	m.clearedvirtualusers = true
}

// VirtualusersCleared reports if the "virtualusers" edge to the VirtualUser entity was cleared.
func (m *HostMutation) VirtualusersCleared() bool {
	return m.clearedvirtualusers
}

// RemoveVirtualuserIDs removes the "virtualusers" edge to the VirtualUser entity by IDs.
func (m *HostMutation) RemoveVirtualuserIDs(ids ...int) {
	if m.removedvirtualusers == nil {
		m.removedvirtualusers = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.virtualusers, ids[i])
		m.removedvirtualusers[ids[i]] = struct{}{}
	}
}

// RemovedVirtualusers returns the removed IDs of the "virtualusers" edge to the VirtualUser entity.
func (m *HostMutation) RemovedVirtualusersIDs() (ids []int) {
	for id := range m.removedvirtualusers {
		ids = append(ids, id)
	}
	return
}

// VirtualusersIDs returns the "virtualusers" edge IDs in the mutation.
func (m *HostMutation) VirtualusersIDs() (ids []int) {
	for id := range m.virtualusers {
		ids = append(ids, id)
	}
	return
}

// ResetVirtualusers resets all changes to the "virtualusers" edge.
func (m *HostMutation) ResetVirtualusers() {
	m.virtualusers = nil
	m.clearedvirtualusers = false
	m.removedvirtualusers = nil
}

// AddHackerIDs adds the "hackers" edge to the User entity by ids.
func (m *HostMutation) AddHackerIDs(ids ...int) {
	if m.hackers == nil {
		m.hackers = make(map[int]struct{})
	}
	for i := range ids {
		m.hackers[ids[i]] = struct{}{}
	}
}

// ClearHackers clears the "hackers" edge to the User entity.
func (m *HostMutation) ClearHackers() {
	m.clearedhackers = true
}

// HackersCleared reports if the "hackers" edge to the User entity was cleared.
func (m *HostMutation) HackersCleared() bool {
	return m.clearedhackers
}

// RemoveHackerIDs removes the "hackers" edge to the User entity by IDs.
func (m *HostMutation) RemoveHackerIDs(ids ...int) {
	if m.removedhackers == nil {
		m.removedhackers = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.hackers, ids[i])
		m.removedhackers[ids[i]] = struct{}{}
	}
}

// RemovedHackers returns the removed IDs of the "hackers" edge to the User entity.
func (m *HostMutation) RemovedHackersIDs() (ids []int) {
	for id := range m.removedhackers {
		ids = append(ids, id)
	}
	return
}

// HackersIDs returns the "hackers" edge IDs in the mutation.
func (m *HostMutation) HackersIDs() (ids []int) {
	for id := range m.hackers {
		ids = append(ids, id)
	}
	return
}

// ResetHackers resets all changes to the "hackers" edge.
func (m *HostMutation) ResetHackers() {
	m.hackers = nil
	m.clearedhackers = false
	m.removedhackers = nil
}

// Where appends a list predicates to the HostMutation builder.
func (m *HostMutation) Where(ps ...predicate.Host) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the HostMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *HostMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Host, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *HostMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *HostMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Host).
func (m *HostMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *HostMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.name != nil {
		fields = append(fields, host.FieldName)
	}
	if m._type != nil {
		fields = append(fields, host.FieldType)
	}
	if m.entry != nil {
		fields = append(fields, host.FieldEntry)
	}
	if m.machine_type != nil {
		fields = append(fields, host.FieldMachineType)
	}
	if m.organization != nil {
		fields = append(fields, host.FieldOrganization)
	}
	if m.contact != nil {
		fields = append(fields, host.FieldContact)
	}
	if m.contact_address != nil {
		fields = append(fields, host.FieldContactAddress)
	}
	if m.country != nil {
		fields = append(fields, host.FieldCountry)
	}
	if m.location != nil {
		fields = append(fields, host.FieldLocation)
	}
	if m.geo_location != nil {
		fields = append(fields, host.FieldGeoLocation)
	}
	if m.phone != nil {
		fields = append(fields, host.FieldPhone)
	}
	if m.neighbours != nil {
		fields = append(fields, host.FieldNeighbours)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *HostMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case host.FieldName:
		return m.Name()
	case host.FieldType:
		return m.GetType()
	case host.FieldEntry:
		return m.Entry()
	case host.FieldMachineType:
		return m.MachineType()
	case host.FieldOrganization:
		return m.Organization()
	case host.FieldContact:
		return m.Contact()
	case host.FieldContactAddress:
		return m.ContactAddress()
	case host.FieldCountry:
		return m.Country()
	case host.FieldLocation:
		return m.Location()
	case host.FieldGeoLocation:
		return m.GeoLocation()
	case host.FieldPhone:
		return m.Phone()
	case host.FieldNeighbours:
		return m.Neighbours()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *HostMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case host.FieldName:
		return m.OldName(ctx)
	case host.FieldType:
		return m.OldType(ctx)
	case host.FieldEntry:
		return m.OldEntry(ctx)
	case host.FieldMachineType:
		return m.OldMachineType(ctx)
	case host.FieldOrganization:
		return m.OldOrganization(ctx)
	case host.FieldContact:
		return m.OldContact(ctx)
	case host.FieldContactAddress:
		return m.OldContactAddress(ctx)
	case host.FieldCountry:
		return m.OldCountry(ctx)
	case host.FieldLocation:
		return m.OldLocation(ctx)
	case host.FieldGeoLocation:
		return m.OldGeoLocation(ctx)
	case host.FieldPhone:
		return m.OldPhone(ctx)
	case host.FieldNeighbours:
		return m.OldNeighbours(ctx)
	}
	return nil, fmt.Errorf("unknown Host field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HostMutation) SetField(name string, value ent.Value) error {
	switch name {
	case host.FieldName:
		v, ok := value.(schema.HostName)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case host.FieldType:
		v, ok := value.(host.Type)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case host.FieldEntry:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEntry(v)
		return nil
	case host.FieldMachineType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMachineType(v)
		return nil
	case host.FieldOrganization:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrganization(v)
		return nil
	case host.FieldContact:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContact(v)
		return nil
	case host.FieldContactAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContactAddress(v)
		return nil
	case host.FieldCountry:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCountry(v)
		return nil
	case host.FieldLocation:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLocation(v)
		return nil
	case host.FieldGeoLocation:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGeoLocation(v)
		return nil
	case host.FieldPhone:
		v, ok := value.([]schema.PhoneNumber)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPhone(v)
		return nil
	case host.FieldNeighbours:
		v, ok := value.([]schema.HostName)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNeighbours(v)
		return nil
	}
	return fmt.Errorf("unknown Host field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *HostMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *HostMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HostMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Host numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *HostMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(host.FieldPhone) {
		fields = append(fields, host.FieldPhone)
	}
	if m.FieldCleared(host.FieldNeighbours) {
		fields = append(fields, host.FieldNeighbours)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *HostMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *HostMutation) ClearField(name string) error {
	switch name {
	case host.FieldPhone:
		m.ClearPhone()
		return nil
	case host.FieldNeighbours:
		m.ClearNeighbours()
		return nil
	}
	return fmt.Errorf("unknown Host nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *HostMutation) ResetField(name string) error {
	switch name {
	case host.FieldName:
		m.ResetName()
		return nil
	case host.FieldType:
		m.ResetType()
		return nil
	case host.FieldEntry:
		m.ResetEntry()
		return nil
	case host.FieldMachineType:
		m.ResetMachineType()
		return nil
	case host.FieldOrganization:
		m.ResetOrganization()
		return nil
	case host.FieldContact:
		m.ResetContact()
		return nil
	case host.FieldContactAddress:
		m.ResetContactAddress()
		return nil
	case host.FieldCountry:
		m.ResetCountry()
		return nil
	case host.FieldLocation:
		m.ResetLocation()
		return nil
	case host.FieldGeoLocation:
		m.ResetGeoLocation()
		return nil
	case host.FieldPhone:
		m.ResetPhone()
		return nil
	case host.FieldNeighbours:
		m.ResetNeighbours()
		return nil
	}
	return fmt.Errorf("unknown Host field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *HostMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.services != nil {
		edges = append(edges, host.EdgeServices)
	}
	if m.virtualusers != nil {
		edges = append(edges, host.EdgeVirtualusers)
	}
	if m.hackers != nil {
		edges = append(edges, host.EdgeHackers)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *HostMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case host.EdgeServices:
		ids := make([]ent.Value, 0, len(m.services))
		for id := range m.services {
			ids = append(ids, id)
		}
		return ids
	case host.EdgeVirtualusers:
		ids := make([]ent.Value, 0, len(m.virtualusers))
		for id := range m.virtualusers {
			ids = append(ids, id)
		}
		return ids
	case host.EdgeHackers:
		ids := make([]ent.Value, 0, len(m.hackers))
		for id := range m.hackers {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *HostMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedservices != nil {
		edges = append(edges, host.EdgeServices)
	}
	if m.removedvirtualusers != nil {
		edges = append(edges, host.EdgeVirtualusers)
	}
	if m.removedhackers != nil {
		edges = append(edges, host.EdgeHackers)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *HostMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case host.EdgeServices:
		ids := make([]ent.Value, 0, len(m.removedservices))
		for id := range m.removedservices {
			ids = append(ids, id)
		}
		return ids
	case host.EdgeVirtualusers:
		ids := make([]ent.Value, 0, len(m.removedvirtualusers))
		for id := range m.removedvirtualusers {
			ids = append(ids, id)
		}
		return ids
	case host.EdgeHackers:
		ids := make([]ent.Value, 0, len(m.removedhackers))
		for id := range m.removedhackers {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *HostMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedservices {
		edges = append(edges, host.EdgeServices)
	}
	if m.clearedvirtualusers {
		edges = append(edges, host.EdgeVirtualusers)
	}
	if m.clearedhackers {
		edges = append(edges, host.EdgeHackers)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *HostMutation) EdgeCleared(name string) bool {
	switch name {
	case host.EdgeServices:
		return m.clearedservices
	case host.EdgeVirtualusers:
		return m.clearedvirtualusers
	case host.EdgeHackers:
		return m.clearedhackers
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *HostMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Host unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *HostMutation) ResetEdge(name string) error {
	switch name {
	case host.EdgeServices:
		m.ResetServices()
		return nil
	case host.EdgeVirtualusers:
		m.ResetVirtualusers()
		return nil
	case host.EdgeHackers:
		m.ResetHackers()
		return nil
	}
	return fmt.Errorf("unknown Host edge %s", name)
}

// JokeMutation represents an operation that mutates the Joke nodes in the graph.
type JokeMutation struct {
	config
	op            Op
	typ           string
	id            *int
	body          *string
	category      *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Joke, error)
	predicates    []predicate.Joke
}

var _ ent.Mutation = (*JokeMutation)(nil)

// jokeOption allows management of the mutation configuration using functional options.
type jokeOption func(*JokeMutation)

// newJokeMutation creates new mutation for the Joke entity.
func newJokeMutation(c config, op Op, opts ...jokeOption) *JokeMutation {
	m := &JokeMutation{
		config:        c,
		op:            op,
		typ:           TypeJoke,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withJokeID sets the ID field of the mutation.
func withJokeID(id int) jokeOption {
	return func(m *JokeMutation) {
		var (
			err   error
			once  sync.Once
			value *Joke
		)
		m.oldValue = func(ctx context.Context) (*Joke, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Joke.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withJoke sets the old Joke of the mutation.
func withJoke(node *Joke) jokeOption {
	return func(m *JokeMutation) {
		m.oldValue = func(context.Context) (*Joke, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m JokeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m JokeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Joke entities.
func (m *JokeMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *JokeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *JokeMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Joke.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetBody sets the "body" field.
func (m *JokeMutation) SetBody(s string) {
	m.body = &s
}

// Body returns the value of the "body" field in the mutation.
func (m *JokeMutation) Body() (r string, exists bool) {
	v := m.body
	if v == nil {
		return
	}
	return *v, true
}

// OldBody returns the old "body" field's value of the Joke entity.
// If the Joke object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JokeMutation) OldBody(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBody: %w", err)
	}
	return oldValue.Body, nil
}

// ResetBody resets all changes to the "body" field.
func (m *JokeMutation) ResetBody() {
	m.body = nil
}

// SetCategory sets the "category" field.
func (m *JokeMutation) SetCategory(s string) {
	m.category = &s
}

// Category returns the value of the "category" field in the mutation.
func (m *JokeMutation) Category() (r string, exists bool) {
	v := m.category
	if v == nil {
		return
	}
	return *v, true
}

// OldCategory returns the old "category" field's value of the Joke entity.
// If the Joke object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JokeMutation) OldCategory(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCategory is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCategory requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCategory: %w", err)
	}
	return oldValue.Category, nil
}

// ResetCategory resets all changes to the "category" field.
func (m *JokeMutation) ResetCategory() {
	m.category = nil
}

// Where appends a list predicates to the JokeMutation builder.
func (m *JokeMutation) Where(ps ...predicate.Joke) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the JokeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *JokeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Joke, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *JokeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *JokeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Joke).
func (m *JokeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *JokeMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.body != nil {
		fields = append(fields, joke.FieldBody)
	}
	if m.category != nil {
		fields = append(fields, joke.FieldCategory)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *JokeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case joke.FieldBody:
		return m.Body()
	case joke.FieldCategory:
		return m.Category()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *JokeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case joke.FieldBody:
		return m.OldBody(ctx)
	case joke.FieldCategory:
		return m.OldCategory(ctx)
	}
	return nil, fmt.Errorf("unknown Joke field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *JokeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case joke.FieldBody:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBody(v)
		return nil
	case joke.FieldCategory:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCategory(v)
		return nil
	}
	return fmt.Errorf("unknown Joke field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *JokeMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *JokeMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *JokeMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Joke numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *JokeMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *JokeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *JokeMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Joke nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *JokeMutation) ResetField(name string) error {
	switch name {
	case joke.FieldBody:
		m.ResetBody()
		return nil
	case joke.FieldCategory:
		m.ResetCategory()
		return nil
	}
	return fmt.Errorf("unknown Joke field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *JokeMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *JokeMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *JokeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *JokeMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *JokeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *JokeMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *JokeMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Joke unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *JokeMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Joke edge %s", name)
}

// TcpServiceMutation represents an operation that mutates the TcpService nodes in the graph.
type TcpServiceMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	port          *int
	addport       *int
	description   *string
	clearedFields map[string]struct{}
	hosts         map[int]struct{}
	removedhosts  map[int]struct{}
	clearedhosts  bool
	done          bool
	oldValue      func(context.Context) (*TcpService, error)
	predicates    []predicate.TcpService
}

var _ ent.Mutation = (*TcpServiceMutation)(nil)

// tcpserviceOption allows management of the mutation configuration using functional options.
type tcpserviceOption func(*TcpServiceMutation)

// newTcpServiceMutation creates new mutation for the TcpService entity.
func newTcpServiceMutation(c config, op Op, opts ...tcpserviceOption) *TcpServiceMutation {
	m := &TcpServiceMutation{
		config:        c,
		op:            op,
		typ:           TypeTcpService,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTcpServiceID sets the ID field of the mutation.
func withTcpServiceID(id int) tcpserviceOption {
	return func(m *TcpServiceMutation) {
		var (
			err   error
			once  sync.Once
			value *TcpService
		)
		m.oldValue = func(ctx context.Context) (*TcpService, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TcpService.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTcpService sets the old TcpService of the mutation.
func withTcpService(node *TcpService) tcpserviceOption {
	return func(m *TcpServiceMutation) {
		m.oldValue = func(context.Context) (*TcpService, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TcpServiceMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TcpServiceMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TcpServiceMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TcpServiceMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TcpService.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *TcpServiceMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *TcpServiceMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the TcpService entity.
// If the TcpService object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TcpServiceMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *TcpServiceMutation) ResetName() {
	m.name = nil
}

// SetPort sets the "port" field.
func (m *TcpServiceMutation) SetPort(i int) {
	m.port = &i
	m.addport = nil
}

// Port returns the value of the "port" field in the mutation.
func (m *TcpServiceMutation) Port() (r int, exists bool) {
	v := m.port
	if v == nil {
		return
	}
	return *v, true
}

// OldPort returns the old "port" field's value of the TcpService entity.
// If the TcpService object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TcpServiceMutation) OldPort(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPort is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPort requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPort: %w", err)
	}
	return oldValue.Port, nil
}

// AddPort adds i to the "port" field.
func (m *TcpServiceMutation) AddPort(i int) {
	if m.addport != nil {
		*m.addport += i
	} else {
		m.addport = &i
	}
}

// AddedPort returns the value that was added to the "port" field in this mutation.
func (m *TcpServiceMutation) AddedPort() (r int, exists bool) {
	v := m.addport
	if v == nil {
		return
	}
	return *v, true
}

// ResetPort resets all changes to the "port" field.
func (m *TcpServiceMutation) ResetPort() {
	m.port = nil
	m.addport = nil
}

// SetDescription sets the "description" field.
func (m *TcpServiceMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *TcpServiceMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the TcpService entity.
// If the TcpService object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TcpServiceMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *TcpServiceMutation) ResetDescription() {
	m.description = nil
}

// AddHostIDs adds the "hosts" edge to the Host entity by ids.
func (m *TcpServiceMutation) AddHostIDs(ids ...int) {
	if m.hosts == nil {
		m.hosts = make(map[int]struct{})
	}
	for i := range ids {
		m.hosts[ids[i]] = struct{}{}
	}
}

// ClearHosts clears the "hosts" edge to the Host entity.
func (m *TcpServiceMutation) ClearHosts() {
	m.clearedhosts = true
}

// HostsCleared reports if the "hosts" edge to the Host entity was cleared.
func (m *TcpServiceMutation) HostsCleared() bool {
	return m.clearedhosts
}

// RemoveHostIDs removes the "hosts" edge to the Host entity by IDs.
func (m *TcpServiceMutation) RemoveHostIDs(ids ...int) {
	if m.removedhosts == nil {
		m.removedhosts = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.hosts, ids[i])
		m.removedhosts[ids[i]] = struct{}{}
	}
}

// RemovedHosts returns the removed IDs of the "hosts" edge to the Host entity.
func (m *TcpServiceMutation) RemovedHostsIDs() (ids []int) {
	for id := range m.removedhosts {
		ids = append(ids, id)
	}
	return
}

// HostsIDs returns the "hosts" edge IDs in the mutation.
func (m *TcpServiceMutation) HostsIDs() (ids []int) {
	for id := range m.hosts {
		ids = append(ids, id)
	}
	return
}

// ResetHosts resets all changes to the "hosts" edge.
func (m *TcpServiceMutation) ResetHosts() {
	m.hosts = nil
	m.clearedhosts = false
	m.removedhosts = nil
}

// Where appends a list predicates to the TcpServiceMutation builder.
func (m *TcpServiceMutation) Where(ps ...predicate.TcpService) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TcpServiceMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TcpServiceMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TcpService, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TcpServiceMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TcpServiceMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TcpService).
func (m *TcpServiceMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TcpServiceMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, tcpservice.FieldName)
	}
	if m.port != nil {
		fields = append(fields, tcpservice.FieldPort)
	}
	if m.description != nil {
		fields = append(fields, tcpservice.FieldDescription)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TcpServiceMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tcpservice.FieldName:
		return m.Name()
	case tcpservice.FieldPort:
		return m.Port()
	case tcpservice.FieldDescription:
		return m.Description()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TcpServiceMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tcpservice.FieldName:
		return m.OldName(ctx)
	case tcpservice.FieldPort:
		return m.OldPort(ctx)
	case tcpservice.FieldDescription:
		return m.OldDescription(ctx)
	}
	return nil, fmt.Errorf("unknown TcpService field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TcpServiceMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tcpservice.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case tcpservice.FieldPort:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPort(v)
		return nil
	case tcpservice.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	}
	return fmt.Errorf("unknown TcpService field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TcpServiceMutation) AddedFields() []string {
	var fields []string
	if m.addport != nil {
		fields = append(fields, tcpservice.FieldPort)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TcpServiceMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case tcpservice.FieldPort:
		return m.AddedPort()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TcpServiceMutation) AddField(name string, value ent.Value) error {
	switch name {
	case tcpservice.FieldPort:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPort(v)
		return nil
	}
	return fmt.Errorf("unknown TcpService numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TcpServiceMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TcpServiceMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TcpServiceMutation) ClearField(name string) error {
	return fmt.Errorf("unknown TcpService nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TcpServiceMutation) ResetField(name string) error {
	switch name {
	case tcpservice.FieldName:
		m.ResetName()
		return nil
	case tcpservice.FieldPort:
		m.ResetPort()
		return nil
	case tcpservice.FieldDescription:
		m.ResetDescription()
		return nil
	}
	return fmt.Errorf("unknown TcpService field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TcpServiceMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.hosts != nil {
		edges = append(edges, tcpservice.EdgeHosts)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TcpServiceMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case tcpservice.EdgeHosts:
		ids := make([]ent.Value, 0, len(m.hosts))
		for id := range m.hosts {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TcpServiceMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedhosts != nil {
		edges = append(edges, tcpservice.EdgeHosts)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TcpServiceMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case tcpservice.EdgeHosts:
		ids := make([]ent.Value, 0, len(m.removedhosts))
		for id := range m.removedhosts {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TcpServiceMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedhosts {
		edges = append(edges, tcpservice.EdgeHosts)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TcpServiceMutation) EdgeCleared(name string) bool {
	switch name {
	case tcpservice.EdgeHosts:
		return m.clearedhosts
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TcpServiceMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown TcpService unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TcpServiceMutation) ResetEdge(name string) error {
	switch name {
	case tcpservice.EdgeHosts:
		m.ResetHosts()
		return nil
	}
	return fmt.Errorf("unknown TcpService edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                 Op
	typ                string
	id                 *int
	user               *schema.Uname
	password           *schema.PasswordHash
	last_login         *time.Time
	last_login_attempt *time.Time
	clearedFields      map[string]struct{}
	hosts              map[int]struct{}
	removedhosts       map[int]struct{}
	clearedhosts       bool
	done               bool
	oldValue           func(context.Context) (*User, error)
	predicates         []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUser sets the "user" field.
func (m *UserMutation) SetUser(s schema.Uname) {
	m.user = &s
}

// User returns the value of the "user" field in the mutation.
func (m *UserMutation) User() (r schema.Uname, exists bool) {
	v := m.user
	if v == nil {
		return
	}
	return *v, true
}

// OldUser returns the old "user" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUser(ctx context.Context) (v schema.Uname, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUser is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUser requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUser: %w", err)
	}
	return oldValue.User, nil
}

// ResetUser resets all changes to the "user" field.
func (m *UserMutation) ResetUser() {
	m.user = nil
}

// SetPassword sets the "password" field.
func (m *UserMutation) SetPassword(sh schema.PasswordHash) {
	m.password = &sh
}

// Password returns the value of the "password" field in the mutation.
func (m *UserMutation) Password() (r schema.PasswordHash, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old "password" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPassword(ctx context.Context) (v schema.PasswordHash, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ResetPassword resets all changes to the "password" field.
func (m *UserMutation) ResetPassword() {
	m.password = nil
}

// SetLastLogin sets the "last_login" field.
func (m *UserMutation) SetLastLogin(t time.Time) {
	m.last_login = &t
}

// LastLogin returns the value of the "last_login" field in the mutation.
func (m *UserMutation) LastLogin() (r time.Time, exists bool) {
	v := m.last_login
	if v == nil {
		return
	}
	return *v, true
}

// OldLastLogin returns the old "last_login" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldLastLogin(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastLogin is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastLogin requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastLogin: %w", err)
	}
	return oldValue.LastLogin, nil
}

// ClearLastLogin clears the value of the "last_login" field.
func (m *UserMutation) ClearLastLogin() {
	m.last_login = nil
	m.clearedFields[user.FieldLastLogin] = struct{}{}
}

// LastLoginCleared returns if the "last_login" field was cleared in this mutation.
func (m *UserMutation) LastLoginCleared() bool {
	_, ok := m.clearedFields[user.FieldLastLogin]
	return ok
}

// ResetLastLogin resets all changes to the "last_login" field.
func (m *UserMutation) ResetLastLogin() {
	m.last_login = nil
	delete(m.clearedFields, user.FieldLastLogin)
}

// SetLastLoginAttempt sets the "last_login_attempt" field.
func (m *UserMutation) SetLastLoginAttempt(t time.Time) {
	m.last_login_attempt = &t
}

// LastLoginAttempt returns the value of the "last_login_attempt" field in the mutation.
func (m *UserMutation) LastLoginAttempt() (r time.Time, exists bool) {
	v := m.last_login_attempt
	if v == nil {
		return
	}
	return *v, true
}

// OldLastLoginAttempt returns the old "last_login_attempt" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldLastLoginAttempt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastLoginAttempt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastLoginAttempt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastLoginAttempt: %w", err)
	}
	return oldValue.LastLoginAttempt, nil
}

// ClearLastLoginAttempt clears the value of the "last_login_attempt" field.
func (m *UserMutation) ClearLastLoginAttempt() {
	m.last_login_attempt = nil
	m.clearedFields[user.FieldLastLoginAttempt] = struct{}{}
}

// LastLoginAttemptCleared returns if the "last_login_attempt" field was cleared in this mutation.
func (m *UserMutation) LastLoginAttemptCleared() bool {
	_, ok := m.clearedFields[user.FieldLastLoginAttempt]
	return ok
}

// ResetLastLoginAttempt resets all changes to the "last_login_attempt" field.
func (m *UserMutation) ResetLastLoginAttempt() {
	m.last_login_attempt = nil
	delete(m.clearedFields, user.FieldLastLoginAttempt)
}

// AddHostIDs adds the "hosts" edge to the Host entity by ids.
func (m *UserMutation) AddHostIDs(ids ...int) {
	if m.hosts == nil {
		m.hosts = make(map[int]struct{})
	}
	for i := range ids {
		m.hosts[ids[i]] = struct{}{}
	}
}

// ClearHosts clears the "hosts" edge to the Host entity.
func (m *UserMutation) ClearHosts() {
	m.clearedhosts = true
}

// HostsCleared reports if the "hosts" edge to the Host entity was cleared.
func (m *UserMutation) HostsCleared() bool {
	return m.clearedhosts
}

// RemoveHostIDs removes the "hosts" edge to the Host entity by IDs.
func (m *UserMutation) RemoveHostIDs(ids ...int) {
	if m.removedhosts == nil {
		m.removedhosts = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.hosts, ids[i])
		m.removedhosts[ids[i]] = struct{}{}
	}
}

// RemovedHosts returns the removed IDs of the "hosts" edge to the Host entity.
func (m *UserMutation) RemovedHostsIDs() (ids []int) {
	for id := range m.removedhosts {
		ids = append(ids, id)
	}
	return
}

// HostsIDs returns the "hosts" edge IDs in the mutation.
func (m *UserMutation) HostsIDs() (ids []int) {
	for id := range m.hosts {
		ids = append(ids, id)
	}
	return
}

// ResetHosts resets all changes to the "hosts" edge.
func (m *UserMutation) ResetHosts() {
	m.hosts = nil
	m.clearedhosts = false
	m.removedhosts = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.user != nil {
		fields = append(fields, user.FieldUser)
	}
	if m.password != nil {
		fields = append(fields, user.FieldPassword)
	}
	if m.last_login != nil {
		fields = append(fields, user.FieldLastLogin)
	}
	if m.last_login_attempt != nil {
		fields = append(fields, user.FieldLastLoginAttempt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldUser:
		return m.User()
	case user.FieldPassword:
		return m.Password()
	case user.FieldLastLogin:
		return m.LastLogin()
	case user.FieldLastLoginAttempt:
		return m.LastLoginAttempt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldUser:
		return m.OldUser(ctx)
	case user.FieldPassword:
		return m.OldPassword(ctx)
	case user.FieldLastLogin:
		return m.OldLastLogin(ctx)
	case user.FieldLastLoginAttempt:
		return m.OldLastLoginAttempt(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldUser:
		v, ok := value.(schema.Uname)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUser(v)
		return nil
	case user.FieldPassword:
		v, ok := value.(schema.PasswordHash)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	case user.FieldLastLogin:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastLogin(v)
		return nil
	case user.FieldLastLoginAttempt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastLoginAttempt(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(user.FieldLastLogin) {
		fields = append(fields, user.FieldLastLogin)
	}
	if m.FieldCleared(user.FieldLastLoginAttempt) {
		fields = append(fields, user.FieldLastLoginAttempt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	switch name {
	case user.FieldLastLogin:
		m.ClearLastLogin()
		return nil
	case user.FieldLastLoginAttempt:
		m.ClearLastLoginAttempt()
		return nil
	}
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldUser:
		m.ResetUser()
		return nil
	case user.FieldPassword:
		m.ResetPassword()
		return nil
	case user.FieldLastLogin:
		m.ResetLastLogin()
		return nil
	case user.FieldLastLoginAttempt:
		m.ResetLastLoginAttempt()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.hosts != nil {
		edges = append(edges, user.EdgeHosts)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeHosts:
		ids := make([]ent.Value, 0, len(m.hosts))
		for id := range m.hosts {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedhosts != nil {
		edges = append(edges, user.EdgeHosts)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeHosts:
		ids := make([]ent.Value, 0, len(m.removedhosts))
		for id := range m.removedhosts {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedhosts {
		edges = append(edges, user.EdgeHosts)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeHosts:
		return m.clearedhosts
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeHosts:
		m.ResetHosts()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}

// VirtualUserMutation represents an operation that mutates the VirtualUser nodes in the graph.
type VirtualUserMutation struct {
	config
	op            Op
	typ           string
	id            *int
	user          *schema.Uname
	password      *schema.Password
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*VirtualUser, error)
	predicates    []predicate.VirtualUser
}

var _ ent.Mutation = (*VirtualUserMutation)(nil)

// virtualuserOption allows management of the mutation configuration using functional options.
type virtualuserOption func(*VirtualUserMutation)

// newVirtualUserMutation creates new mutation for the VirtualUser entity.
func newVirtualUserMutation(c config, op Op, opts ...virtualuserOption) *VirtualUserMutation {
	m := &VirtualUserMutation{
		config:        c,
		op:            op,
		typ:           TypeVirtualUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withVirtualUserID sets the ID field of the mutation.
func withVirtualUserID(id int) virtualuserOption {
	return func(m *VirtualUserMutation) {
		var (
			err   error
			once  sync.Once
			value *VirtualUser
		)
		m.oldValue = func(ctx context.Context) (*VirtualUser, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().VirtualUser.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withVirtualUser sets the old VirtualUser of the mutation.
func withVirtualUser(node *VirtualUser) virtualuserOption {
	return func(m *VirtualUserMutation) {
		m.oldValue = func(context.Context) (*VirtualUser, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m VirtualUserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m VirtualUserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *VirtualUserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *VirtualUserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().VirtualUser.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUser sets the "user" field.
func (m *VirtualUserMutation) SetUser(s schema.Uname) {
	m.user = &s
}

// User returns the value of the "user" field in the mutation.
func (m *VirtualUserMutation) User() (r schema.Uname, exists bool) {
	v := m.user
	if v == nil {
		return
	}
	return *v, true
}

// OldUser returns the old "user" field's value of the VirtualUser entity.
// If the VirtualUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VirtualUserMutation) OldUser(ctx context.Context) (v schema.Uname, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUser is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUser requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUser: %w", err)
	}
	return oldValue.User, nil
}

// ResetUser resets all changes to the "user" field.
func (m *VirtualUserMutation) ResetUser() {
	m.user = nil
}

// SetPassword sets the "password" field.
func (m *VirtualUserMutation) SetPassword(s schema.Password) {
	m.password = &s
}

// Password returns the value of the "password" field in the mutation.
func (m *VirtualUserMutation) Password() (r schema.Password, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old "password" field's value of the VirtualUser entity.
// If the VirtualUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VirtualUserMutation) OldPassword(ctx context.Context) (v schema.Password, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ResetPassword resets all changes to the "password" field.
func (m *VirtualUserMutation) ResetPassword() {
	m.password = nil
}

// Where appends a list predicates to the VirtualUserMutation builder.
func (m *VirtualUserMutation) Where(ps ...predicate.VirtualUser) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the VirtualUserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *VirtualUserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.VirtualUser, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *VirtualUserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *VirtualUserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (VirtualUser).
func (m *VirtualUserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *VirtualUserMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.user != nil {
		fields = append(fields, virtualuser.FieldUser)
	}
	if m.password != nil {
		fields = append(fields, virtualuser.FieldPassword)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *VirtualUserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case virtualuser.FieldUser:
		return m.User()
	case virtualuser.FieldPassword:
		return m.Password()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *VirtualUserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case virtualuser.FieldUser:
		return m.OldUser(ctx)
	case virtualuser.FieldPassword:
		return m.OldPassword(ctx)
	}
	return nil, fmt.Errorf("unknown VirtualUser field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VirtualUserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case virtualuser.FieldUser:
		v, ok := value.(schema.Uname)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUser(v)
		return nil
	case virtualuser.FieldPassword:
		v, ok := value.(schema.Password)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	}
	return fmt.Errorf("unknown VirtualUser field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *VirtualUserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *VirtualUserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VirtualUserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown VirtualUser numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *VirtualUserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *VirtualUserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *VirtualUserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown VirtualUser nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *VirtualUserMutation) ResetField(name string) error {
	switch name {
	case virtualuser.FieldUser:
		m.ResetUser()
		return nil
	case virtualuser.FieldPassword:
		m.ResetPassword()
		return nil
	}
	return fmt.Errorf("unknown VirtualUser field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *VirtualUserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *VirtualUserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *VirtualUserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *VirtualUserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *VirtualUserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *VirtualUserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *VirtualUserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown VirtualUser unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *VirtualUserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown VirtualUser edge %s", name)
}
