// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/encse/altnet/ent/predicate"
	"github.com/encse/altnet/ent/tcpservice"
)

// TcpServiceDelete is the builder for deleting a TcpService entity.
type TcpServiceDelete struct {
	config
	hooks    []Hook
	mutation *TcpServiceMutation
}

// Where appends a list predicates to the TcpServiceDelete builder.
func (tsd *TcpServiceDelete) Where(ps ...predicate.TcpService) *TcpServiceDelete {
	tsd.mutation.Where(ps...)
	return tsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tsd *TcpServiceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, TcpServiceMutation](ctx, tsd.sqlExec, tsd.mutation, tsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tsd *TcpServiceDelete) ExecX(ctx context.Context) int {
	n, err := tsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tsd *TcpServiceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tcpservice.Table, sqlgraph.NewFieldSpec(tcpservice.FieldID, field.TypeInt))
	if ps := tsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tsd.mutation.done = true
	return affected, err
}

// TcpServiceDeleteOne is the builder for deleting a single TcpService entity.
type TcpServiceDeleteOne struct {
	tsd *TcpServiceDelete
}

// Where appends a list predicates to the TcpServiceDelete builder.
func (tsdo *TcpServiceDeleteOne) Where(ps ...predicate.TcpService) *TcpServiceDeleteOne {
	tsdo.tsd.mutation.Where(ps...)
	return tsdo
}

// Exec executes the deletion query.
func (tsdo *TcpServiceDeleteOne) Exec(ctx context.Context) error {
	n, err := tsdo.tsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tcpservice.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tsdo *TcpServiceDeleteOne) ExecX(ctx context.Context) {
	if err := tsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
