// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/encse/altnet/ent/virtualuser"
	"github.com/encse/altnet/schema"
)

// VirtualUserCreate is the builder for creating a VirtualUser entity.
type VirtualUserCreate struct {
	config
	mutation *VirtualUserMutation
	hooks    []Hook
}

// SetUser sets the "user" field.
func (vuc *VirtualUserCreate) SetUser(s schema.Uname) *VirtualUserCreate {
	vuc.mutation.SetUser(s)
	return vuc
}

// SetPassword sets the "password" field.
func (vuc *VirtualUserCreate) SetPassword(s schema.Password) *VirtualUserCreate {
	vuc.mutation.SetPassword(s)
	return vuc
}

// Mutation returns the VirtualUserMutation object of the builder.
func (vuc *VirtualUserCreate) Mutation() *VirtualUserMutation {
	return vuc.mutation
}

// Save creates the VirtualUser in the database.
func (vuc *VirtualUserCreate) Save(ctx context.Context) (*VirtualUser, error) {
	return withHooks[*VirtualUser, VirtualUserMutation](ctx, vuc.sqlSave, vuc.mutation, vuc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (vuc *VirtualUserCreate) SaveX(ctx context.Context) *VirtualUser {
	v, err := vuc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vuc *VirtualUserCreate) Exec(ctx context.Context) error {
	_, err := vuc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vuc *VirtualUserCreate) ExecX(ctx context.Context) {
	if err := vuc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vuc *VirtualUserCreate) check() error {
	if _, ok := vuc.mutation.User(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required field "VirtualUser.user"`)}
	}
	if _, ok := vuc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "VirtualUser.password"`)}
	}
	return nil
}

func (vuc *VirtualUserCreate) sqlSave(ctx context.Context) (*VirtualUser, error) {
	if err := vuc.check(); err != nil {
		return nil, err
	}
	_node, _spec := vuc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vuc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	vuc.mutation.id = &_node.ID
	vuc.mutation.done = true
	return _node, nil
}

func (vuc *VirtualUserCreate) createSpec() (*VirtualUser, *sqlgraph.CreateSpec) {
	var (
		_node = &VirtualUser{config: vuc.config}
		_spec = sqlgraph.NewCreateSpec(virtualuser.Table, sqlgraph.NewFieldSpec(virtualuser.FieldID, field.TypeInt))
	)
	if value, ok := vuc.mutation.User(); ok {
		_spec.SetField(virtualuser.FieldUser, field.TypeString, value)
		_node.User = value
	}
	if value, ok := vuc.mutation.Password(); ok {
		_spec.SetField(virtualuser.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	return _node, _spec
}

// VirtualUserCreateBulk is the builder for creating many VirtualUser entities in bulk.
type VirtualUserCreateBulk struct {
	config
	builders []*VirtualUserCreate
}

// Save creates the VirtualUser entities in the database.
func (vucb *VirtualUserCreateBulk) Save(ctx context.Context) ([]*VirtualUser, error) {
	specs := make([]*sqlgraph.CreateSpec, len(vucb.builders))
	nodes := make([]*VirtualUser, len(vucb.builders))
	mutators := make([]Mutator, len(vucb.builders))
	for i := range vucb.builders {
		func(i int, root context.Context) {
			builder := vucb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VirtualUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vucb *VirtualUserCreateBulk) SaveX(ctx context.Context) []*VirtualUser {
	v, err := vucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vucb *VirtualUserCreateBulk) Exec(ctx context.Context) error {
	_, err := vucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vucb *VirtualUserCreateBulk) ExecX(ctx context.Context) {
	if err := vucb.Exec(ctx); err != nil {
		panic(err)
	}
}
