// Code generated by ent, DO NOT EDIT.

package joke

const (
	// Label holds the string label denoting the joke type in the database.
	Label = "joke"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// Table holds the table name of the joke in the database.
	Table = "jokes"
)

// Columns holds all SQL columns for joke fields.
var Columns = []string{
	FieldID,
	FieldBody,
	FieldCategory,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
